### ISSUE TITLE
text with no spaces length too long

### ISSUE THREAD

**Issue by soundslikeodd** [tomi-vanek/asciiart-logo#6]
Issue: 

If the text passed to a text function is long the code crashes.

Example code:
```javascript
#!/usr/bin/env node
const logo = require('asciiart-logo');

console.log(logo({
    name: 'name',
    font: 'Rectangles',
    lineChars: 18,
    padding: 2,
    margin: 1,
})
    .wrap('averylongstringthathasnospaces-againaverylongstring')
    .render());
```

Error output (sanitized):
```
/node_modules/asciiart-logo/logo.js:70
    const rightPadding = rightSpaces ? ' '.repeat(rightSpaces)  : '';
                                           ^

RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at _render (/node_modules/asciiart-logo/logo.js:70:44)
    at lineLeft (/node_modules/asciiart-logo/logo.js:81:37)
    at /node_modules/asciiart-logo/logo.js:94:9
    at Array.map (<anonymous>)
    at wordWrap (/node_modules/asciiart-logo/logo.js:91:6)
    at Object.wrap (/node_modules/asciiart-logo/logo.js:114:29)
    at Object.<anonymous> (/tools/testLogo.js:11:5)
```

Comments:

I believe this issue stems from `panelTextWidth` being calculated based off of the `name` option.  When the extra space for the text functions are calculated a negative number is calculated and JS String's `repeat` function can not take a negative number, [String.prototype.repeat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#parameters).

**Comment by soundslikeodd** [comment]
#7

**Comment by tomi-vanek** [comment]
fixed by https://github.com/tomi-vanek/asciiart-logo/pull/7
